apiVersion: v2
description: Mattermost Enterprise server with high availitibity.
name: mattermost-enterprise-edition
version: 1.12.0
appVersion: 5.29.0
keywords:
  - mattermost
  - communication
  - messaging
  - team colaboration
home: https://mattermost.com
icon: http://www.mattermost.org/wp-content/uploads/2016/04/icon.png
maintainers:
  - name: cpanato
    email: carlos@mattermost.com
  - name: jwilander
    email: joram@mattermost.com
  - name: stylianosrigas
    email: stylianos@mattermost.com
sources:
  - https://github.com/mattermost/mattermost-server
  - https://github.com/mattermost/mattermost-helm
dependencies:
  - name: mysqlha
    repository: https://charts.helm.sh/incubator
    version: 2.0.0
    condition: global.features.database.useInternal
  - name: minio
    repository: https://charts.helm.sh/stable
    version: 5.0.26
    condition: minio.enabled
  - name: prometheus
    repository: https://charts.helm.sh/stable
    version: 11.4.0
    condition: global.features.grafana.enabled
